In [5]:
i = int = 0
user = input("Введите что-нибудь:")
print(user[len(user)-1], end="")
while (i != len(user)-2):    
    i+=1
    print(user[i], end="")
print(user[0],end="")

Введите что-нибудь:qwerty
ywertq

In [4]:
a = int(input("Введите натурально число:"))

def F (n):
    if n > 1 :return n * F(n-1)
    elif n == 1: return 1
    elif n < 0: return "Ошибка"
    else : return 1 
    
F (a)

Введите натурально число:3


6

In [3]:
from random import randint
a = randint(0,2)
mas = ['rock', 'scissors', 'paper']
print ("Введите 'rock', 'scissors' или 'paper' для начала игры")

def UserChoice():
    c = int = 0
    userk = input("Выберите бойца:")
    print()    
    if userk == 'rock' or userk == 'Rock': 
        c = 0        
        Game(c)
    elif userk == 'scissors' or userk == 'Scissors': 
        c = 1       
        Game(c)
    elif userk == 'paper' or userk == 'Paper': 
        c = 2        
        Game(c)
    else:
        print("Ошибка")
        UserChoice()       


def Game(b):
    
    if (b == 0) and (a == 1) : print('Вы победили!')
    elif (b == 0) and (a == 2) : print('Вы проиграли!')
    elif (b == 0) and (a == 0) : print('Ничья!')
        
    if (b == 1) and (a == 2) : print('Вы победили!')
    elif (b == 1) and (a == 0) : print('Вы проиграли!')
    elif (b == 1) and (a == 1) : print('Ничья!')
        
    if (b == 2) and (a == 0) : print('Вы победили!') 
    elif (b == 2) and (a == 1) : print('Вы проиграли!')
    elif (b == 2) and (a == 2) : print('Ничья!')
        
    print("Противник выбрал:", mas[a])
    
UserChoice() 



Введите 'rock', 'scissors' или 'paper' для начала игры
Выберите бойца:rock

Ничья!
Противник выбрал: rock


In [2]:
from random import randint

b = int(input()) # Массивы
a = int(input()) # Элементы

Bigmas = [[i for i in range(a)]]
for i in range (b-1):
    Bigmas += [[i for i in range(a)]]
for T in range (b):
    for Y in range(a):
        Bigmas[T][Y] = randint(0,100)
        
print(Bigmas)

3
2
[[71, 65], [42, 44], [61, 30]]


In [1]:
import numpy as np
import random 
m=[1,-1] 
summ=0
l=0
n=int(input())
a=np.zeros((n,n))

for i in range(n):
    for j in range(n):
        a[i,j]=random.choice(m)
print(a)

for i in range(n):
    for j in range(n):
        summ+=a[i,j]*a[i,j-1]
        l+=a[i-1,j]*a[i,j]        
print(summ+l)

5
[[ 1.  1. -1. -1. -1.]
 [-1. -1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.]
 [-1.  1.  1. -1.  1.]
 [ 1.  1. -1.  1. -1.]]
-6.0
